In [62]:
import numpy as np 
x=[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60]
array_x=np.array(x)
array_x=np.arange(2, 61, 2)
array_x=array_x.reshape(5,2,3)
print(array_x)

[[[ 2  4  6]
  [ 8 10 12]]

 [[14 16 18]
  [20 22 24]]

 [[26 28 30]
  [32 34 36]]

 [[38 40 42]
  [44 46 48]]

 [[50 52 54]
  [56 58 60]]]


In [61]:
x=np.arange(1,31)
x=x.reshape(5,6)
x

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [63]:
x=np.arange(1,30,2)
print(x)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]


In [65]:
np.array([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]])

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])